server.port=8081

spring.jpa.hibernate.ddl-auto = none
#spring.jpa.hibernate.ddl-auto = create
#spring.jpa.hibernate.ddl-auto = update
#spring.jpa.hibernate.ddl-auto = create-drop
# dinh dang thao tac jpa


spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL55Dialect
# dialect dinh nghia cai csdl tuong ung nao hibernate sinh code 
spring.jpa.properties.hibernate.enable_lazy_load_no_trans = true
# dung de hibernate sinh ra cau truy van phu hop

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
# show cau truy van

spring.profiles.active=dev
#moi truong 

dev.nguyen = QuyetNguyen